---

services:
  db:
    image: postgres:15
    container_name: pokesag_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: pokesag
      POSTGRES_PASSWORD: pokesag
    volumes:
      - pokesag_db:/var/lib/postgresql/data

  web:
    image: ghcr.io/dmptrluke/pokesag-web:master
    container_name: pokesag_web
    restart: unless-stopped
    build:
      context: ./web
      dockerfile: Dockerfile
      args:
        BUILD_MODE: "development"
    ports:
      - "8400:8000"
    depends_on:
      - db

  receiver:
    image: ghcr.io/dmptrluke/pokesag-receiver:master
    container_name: pokesag_receiver
    restart: unless-stopped
    build:
      context: ./receiver
      dockerfile: Dockerfile
    environment:
      TZ: 'Pacific/Auckland'
      DISCARD_SPAM: 'true'
      # RTL_DEVICE_SERIAL: ''
    depends_on:
      - db
    devices:
      - /dev/bus/usb:/dev/bus/usb
    device_cgroup_rules:
      - 'c 189:* rwm'
    volumes:
      - ./channels.json:/config/channels.json:ro

volumes:
  pokesag_db:
