name: Docker Build

on:
  push:
    branches-ignore:
      - 'dependabot**'
    tags:
      - 'v*'
  pull_request:

jobs:
  build-receiver:
    runs-on: ubuntu-latest
    
        
    permissions:
      packages: write
      contents: read
      
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Set Docker Metadata
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: dmptrluke/pokesag-server,ghcr.io/dmptrluke/pokesag-receiver

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1 
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: ${{ github.event_name != 'pull_request' }}
          context: ./receiver
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          cache-from: type=registry,ref=ghcr.io/dmptrluke/pokesag-receiver:master
          cache-to: type=inline

  build-web:
    runs-on: ubuntu-latest
    
        
    permissions:
      packages: write
      contents: read
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set Docker Metadata
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: dmptrluke/pokesag-web,ghcr.io/dmptrluke/pokesag-web

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1 
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: ${{ github.event_name != 'pull_request' }}
          context: ./web
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          cache-from: type=registry,ref=ghcr.io/dmptrluke/pokesag-web:master
          cache-to: type=inline
