name: Docker Build

on:
  push:
    branches: [ master ]

jobs:
  build-server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./server
          push: true
          tags: dmptrluke/pokesag-server:latest
          cache-from: type=registry,ref=dmptrluke/pokesag-server:latest
          cache-to: type=inline
